spring:
  application:
    name: commitstory

  datasource:
    url: jdbc:h2:mem:commitstory
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/commitstory
    driver-class-name: org.postgresql.Driver
    username: commitstory
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    clean-disabled: true

  h2:
    console:
      enabled: false
